#!/usr/bin/env python3
"""Shared head-emission logic for hand-written and generated pages.

``fix_heads.py`` remains the transform for existing HTML.  Article generation
uses the same functions from this module, so canonical URLs, social tags and
JSON-LD have one implementation and one byte layout.
"""

from __future__ import annotations

import html
import json
from typing import Any

import pagedata
import urlmap


BEGIN = "<!-- seo:begin — generated by scripts/seo/fix_heads.py · do not hand-edit -->"
END = "<!-- seo:end -->"

ORG_ID = f"{urlmap.SITE_ORIGIN}/#organization"
SITE_ID = f"{urlmap.SITE_ORIGIN}/#website"
ORG_LOGO = f"{urlmap.SITE_ORIGIN}/brandbook/xerj-mark.svg"
GITHUB = "https://github.com/xerj-org/xerj"
LICENSE = "https://www.apache.org/licenses/LICENSE-2.0"


def esc(value: str) -> str:
    """Escape an HTML attribute value."""
    return html.escape(value, quote=True)


def text_esc(value: str) -> str:
    """Escape HTML text content."""
    return html.escape(value, quote=False)


def ld(obj: dict[str, Any]) -> str:
    body = json.dumps(obj, ensure_ascii=False, indent=2)
    return f'<script type="application/ld+json">\n{body}\n</script>'


def organization() -> dict[str, Any]:
    return {
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": ORG_ID,
        "name": "XERJ",
        "alternateName": urlmap.SITE_NAME,
        "url": urlmap.SITE_ORIGIN + "/",
        "logo": ORG_LOGO,
        "sameAs": [GITHUB],
    }


def website() -> dict[str, Any]:
    return {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "@id": SITE_ID,
        "name": urlmap.SITE_NAME,
        "url": urlmap.SITE_ORIGIN + "/",
        "inLanguage": "en",
        "publisher": {"@id": ORG_ID},
    }


def _person_or_org(meta: dict[str, Any]) -> dict[str, Any]:
    name = meta.get("author")
    if name:
        return {"@type": "Person", "name": name}
    return {"@id": ORG_ID}


def page_body(rel: str, meta: dict[str, Any], url: str, title: str,
              desc: str, published: str, modified: str) -> dict[str, Any]:
    kind = meta["kind"]
    typ = pagedata.KIND_TYPE[kind]
    img = urlmap.og_image_url()

    if kind == "software":
        return {
            "@context": "https://schema.org",
            "@type": typ,
            "name": "XERJ",
            "alternateName": urlmap.SITE_NAME,
            "applicationCategory": "DeveloperApplication",
            "applicationSubCategory": "Search engine",
            "operatingSystem": "Linux, macOS, Windows",
            "url": url,
            "description": desc,
            "image": img,
            "license": LICENSE,
            "isAccessibleForFree": True,
            "codeRepository": GITHUB,
            "publisher": {"@id": ORG_ID},
            "mainEntityOfPage": {"@type": "WebPage", "@id": url},
        }

    if kind in pagedata.ARTICLE_KINDS:
        body: dict[str, Any] = {
            "@context": "https://schema.org",
            "@type": typ,
            "headline": title,
            "description": desc,
            "url": url,
            "image": img,
            "inLanguage": "en",
            "datePublished": published,
            "dateModified": modified,
            "author": _person_or_org(meta),
            "publisher": {"@id": ORG_ID},
            "isPartOf": {"@id": SITE_ID},
            "mainEntityOfPage": {"@type": "WebPage", "@id": url},
        }
        reviewer = meta.get("reviewer")
        if reviewer:
            body["reviewedBy"] = {"@type": "Person", "name": reviewer}
        return body

    return {
        "@context": "https://schema.org",
        "@type": typ,
        "name": title,
        "description": desc,
        "url": url,
        "image": img,
        "inLanguage": "en",
        "dateModified": modified,
        "isPartOf": {"@id": SITE_ID},
        "mainEntityOfPage": {"@type": "WebPage", "@id": url},
    }


def breadcrumbs(rel: str, meta: dict[str, Any]) -> dict[str, Any] | None:
    """Home > section hubs > this page.  None for the site root."""
    if rel == "index.html":
        return None

    items: list[dict[str, Any]] = [{
        "@type": "ListItem", "position": 1, "name": "Home",
        "item": urlmap.SITE_ORIGIN + "/",
    }]

    parts = rel.split("/")[:-1]
    if rel.endswith("/index.html"):
        parts = parts[:-1]
    for i in range(len(parts)):
        directory = "/".join(parts[:i + 1])
        hub = pagedata.SECTION_HUBS.get(directory)
        if hub is None:
            continue
        label, path = hub
        items.append({
            "@type": "ListItem", "position": len(items) + 1,
            "name": label, "item": urlmap.SITE_ORIGIN + path,
        })

    items.append({
        "@type": "ListItem", "position": len(items) + 1,
        "name": meta["label"],
    })
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": items,
    }


def build_block(rel: str, title: str, desc: str, published: str,
                modified: str, meta: dict[str, Any] | None = None) -> str:
    """Emit the exact SEO block used by ``fix_heads.py``."""
    meta = meta or pagedata.entry(rel)
    url = urlmap.deployed_url(rel)
    img = urlmap.og_image_url()
    og_type = pagedata.KIND_OG_TYPE[meta["kind"]]

    lines = [BEGIN, f'<link rel="canonical" href="{url}">']
    if meta.get("noindex", urlmap.is_noindex(rel)):
        lines.append('<meta name="robots" content="noindex">')

    lines += [
        f'<meta property="og:site_name" content="{esc(urlmap.SITE_NAME)}">',
        f'<meta property="og:type" content="{og_type}">',
        f'<meta property="og:title" content="{esc(title)}">',
        f'<meta property="og:description" content="{esc(desc)}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{img}">',
        f'<meta property="og:image:width" content="{urlmap.OG_IMAGE_WIDTH}">',
        f'<meta property="og:image:height" content="{urlmap.OG_IMAGE_HEIGHT}">',
        f'<meta property="og:image:alt" content="{esc(urlmap.OG_IMAGE_ALT)}">',
        '<meta property="og:locale" content="en_US">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{esc(title)}">',
        f'<meta name="twitter:description" content="{esc(desc)}">',
        f'<meta name="twitter:image" content="{img}">',
        ld(organization()),
        ld(website()),
        ld(page_body(rel, meta, url, title, desc, published, modified)),
    ]
    crumbs = breadcrumbs(rel, meta)
    if crumbs is not None:
        lines.append(ld(crumbs))
    lines.append(END)
    return "\n".join(lines)
