#!/usr/bin/env python3
"""URL mapping — the single source of truth for xerj.org's deployed URL shape.

Cloudflare Pages serves this site with `html_handling: auto-trailing-slash`
(the default), which was verified empirically against the live site on
2026-08-20:

    308  https://xerj.org/product.html     -> https://xerj.org/product
    308  https://xerj.org/docs/index.html  -> https://xerj.org/docs/
    308  https://xerj.org/docs             -> https://xerj.org/docs/
    200  https://xerj.org/

So exactly one URL per file returns 200, and every other spelling of that URL
permanently redirects to it.  `deployed_url()` computes that one string.

Three consumers MUST produce byte-identical strings for a given file:

    * `<link rel="canonical">`   (scripts/seo/fix_heads.py)
    * `<meta property="og:url">` (scripts/seo/fix_heads.py)
    * `<loc>` in sitemap.xml     (scripts/seo/gen_sitemap.py)

They all call `deployed_url()`.  `scripts/seo/seo_lint.py` re-derives the same
value independently from this module and fails the build if any page disagrees.
Do not reimplement this mapping anywhere else.

Primary sources
    https://developers.cloudflare.com/pages/configuration/serving-pages/
    https://developers.cloudflare.com/workers/static-assets/routing/advanced/html-handling/
    https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls
"""

from __future__ import annotations

import datetime as _dt
import pathlib
import re
import subprocess
import sys

# ── constants ───────────────────────────────────────────────────────────────

SITE_ORIGIN = "https://xerj.org"
SITE_NAME = "XERJ.ai"

#: Repo-relative directory that Cloudflare Pages publishes verbatim.
#: (`pages_build_output_dir = "landing"` in wrangler.toml.)
LANDING = "landing"

#: The one Open Graph card, generated by scripts/seo/mk_og_card.py.
OG_IMAGE_PATH = "og/xerj-card.png"
OG_IMAGE_WIDTH = "1200"
OG_IMAGE_HEIGHT = "630"
OG_IMAGE_ALT = "XERJ.ai — the search engine built for AI agents"

#: Pages that carry `<meta name="robots" content="noindex">`.
#:
#: `brandbook/index.html` already declared noindex by hand before this pass;
#: `playground/index.html` is the dashboards SPA shell — zero words, no <h1>,
#: and it collides with the /playground lead-capture gate on the trailing
#: slash alone.  Cloudflare Pages serves `landing/playground.html` at
#: `/playground` and `landing/playground/index.html` at `/playground/`, so two
#: different documents sit one character apart.  Marking the SPA shell noindex
#: keeps them from competing; renaming `playground.html` to `dashboards.html`
#: would cure it properly, but that changes an indexed URL and touches the
#: lead-capture gate, so it is deliberately left alone here.
#:
#: `404.html` is the Cloudflare Pages not-found page.  It is reachable at
#: `/404` as an ordinary document, so without an explicit `noindex` it would
#: be a real indexable page whose whole content is an error message.
NOINDEX: frozenset[str] = frozenset({
    "404.html",
    "brandbook/index.html",
    "playground/index.html",
})

#: Pages deliberately kept out of sitemap.xml.  Google: a `noindex` page must
#: never be advertised in a sitemap — the two signals contradict each other.
#: This set is exactly NOINDEX today; it is kept separate because a page can
#: legitimately be sitemap-excluded without being noindex (e.g. a redirect
#: landing page) and the lint distinguishes the two cases.  `404.html` would
#: belong here even if it were not noindex: a sitemap is a list of pages worth
#: crawling, and the URL that answers every wrong guess is not one of them.
SITEMAP_EXCLUDE: frozenset[str] = frozenset(NOINDEX)

#: Pages that must not receive the generated site-map footer.  None of them
#: loads the site stylesheet, so an injected `.footer-map` would render
#: unstyled — each carries its own self-contained CSS.  They are still
#: *targets* of the footer, which is what the zero-orphan rule actually
#: requires (inbound links, not outbound).
FOOTER_SKIP: frozenset[str] = frozenset({
    "aise-demo.html",         # standalone <style> block, video-only page
    "demo/index.html",        # own design system + own <footer>, no /style.css
    "playground/index.html",  # dashboards SPA shell, own assets/*.css
})

#: Internal hrefs that must not be touched by the .html -> extensionless
#: rewrite because the target is not an HTML page served by Pages' html
#: handling.  Keys are the literal href, values the corrected href.
HREF_FIXUPS: dict[str, str] = {
    # `landing/get` is a FILE (the one-line installer shell script), not a
    # directory — /get/index.html has always been a 404.  The button reading
    # "GET XERJ" belongs on the install page, not on a text/plain script.
    "/get/index.html": "/docs/install",
    # Cloudflare 308s /benchmarks -> /benchmarks/; link the served form.
    "/benchmarks": "/benchmarks/",
}

#: href prefixes/suffixes that are assets, not pages.  Anything matching is
#: left byte-for-byte alone by `rewrite_href`.
_ASSET_SUFFIXES = (
    ".css", ".js", ".mjs", ".json", ".txt", ".xml", ".mp4", ".webm", ".png",
    ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".ico", ".pdf", ".zip", ".gz",
    ".woff", ".woff2", ".ps1", ".sh", ".wasm", ".map",
)
_ASSET_EXACT = frozenset({"/get", "/get.ps1", "/openapi.json"})

_SCHEME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")


# ── file path -> deployed URL ───────────────────────────────────────────────


def deployed_path(rel: str) -> str:
    """Map a landing-relative file path to its deployed absolute path.

    >>> deployed_path("index.html")
    '/'
    >>> deployed_path("product.html")
    '/product'
    >>> deployed_path("docs/index.html")
    '/docs/'
    >>> deployed_path("docs/recipes/hybrid-search.html")
    '/docs/recipes/hybrid-search'
    """
    rel = rel.strip("/")
    if not rel.endswith(".html"):
        raise ValueError(f"not an HTML page: {rel!r}")
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel[: -len(".html")]


def deployed_url(rel: str) -> str:
    """Absolute canonical URL for a landing-relative file path.

    This is *the* function.  canonical, og:url and sitemap <loc> all call it.

    >>> deployed_url("for-agents.html")
    'https://xerj.org/for-agents'
    """
    return SITE_ORIGIN + deployed_path(rel)


def og_image_url() -> str:
    return f"{SITE_ORIGIN}/{OG_IMAGE_PATH}"


# ── deployed URL -> file path ───────────────────────────────────────────────


def rel_for_path(path: str) -> str | None:
    """Inverse of `deployed_path` — the file a deployed path is served from.

    Returns None for paths that cannot name an HTML page.  Tolerates the
    redirecting spellings (`/product.html`, `/docs`, `/docs/index.html`) so the
    lint can report *which* non-canonical form a link used.
    """
    if not path.startswith("/"):
        return None
    path = path.split("#", 1)[0].split("?", 1)[0]
    if path == "/":
        return "index.html"
    body = path[1:]
    if body.endswith("/"):
        return body + "index.html"
    if body.endswith(".html"):
        return body
    return body + ".html"


def rel_for_url(url: str) -> str | None:
    """Inverse of `deployed_url`; None if the URL is off-origin."""
    if url.startswith(SITE_ORIGIN):
        return rel_for_path(url[len(SITE_ORIGIN):] or "/")
    return None


# ── href rewriting ──────────────────────────────────────────────────────────


def is_internal_href(href: str) -> bool:
    """True for hrefs that resolve inside this site and can be rewritten."""
    href = href.strip()
    if not href or href.startswith("#"):
        return False
    if href.startswith("//"):          # protocol-relative — treat as external
        return False
    if _SCHEME_RE.match(href):         # http:, https:, mailto:, tel:, ...
        return False
    return True


def _is_asset(path: str) -> bool:
    if path in _ASSET_EXACT:
        return True
    return path.lower().endswith(_ASSET_SUFFIXES)


def rewrite_href(href: str) -> str:
    """Rewrite one internal href to the URL Cloudflare actually serves.

    `/docs/foo.html` -> `/docs/foo`, `/docs/index.html` -> `/docs/`,
    `/index.html` -> `/`.  Query strings and fragments are preserved.
    External URLs, anchors and assets are returned unchanged.

    Idempotent: rewriting an already-rewritten href is a no-op.
    """
    if not is_internal_href(href):
        return href
    if href in HREF_FIXUPS:
        return HREF_FIXUPS[href]

    path, sep, tail = href.partition("#")
    frag = sep + tail
    path, qsep, query = path.partition("?")
    query = qsep + query

    if path in HREF_FIXUPS:
        return HREF_FIXUPS[path] + query + frag
    if _is_asset(path):
        return href
    if not path.endswith(".html"):
        return href
    if path == "index.html":           # relative form
        return "./" + query + frag
    if path.endswith("/index.html"):
        return path[: -len("index.html")] + query + frag
    return path[: -len(".html")] + query + frag


# ── page discovery ──────────────────────────────────────────────────────────


def iter_pages(root: pathlib.Path) -> list[str]:
    """Every HTML page under `root`, as sorted landing-relative posix paths."""
    return sorted(
        p.relative_to(root).as_posix()
        for p in root.rglob("*.html")
        if p.is_file()
    )


def in_sitemap(rel: str) -> bool:
    return not is_noindex(rel)


def is_noindex(rel: str) -> bool:
    if rel in NOINDEX:
        return True
    # Article sources can opt into noindex without adding a second hand-
    # maintained exclusion list.  The import is lazy to keep this module the
    # dependency-free URL authority used by every SEO script.
    try:
        from article_data import load_for_rel
        article = load_for_rel(repo_root(), rel)
    except (ImportError, OSError):
        article = None
    return bool(article and article.noindex)


# ── git-derived dates ───────────────────────────────────────────────────────


class DateSource:
    """Per-file last/first change dates, from git where possible.

    `git log -1 --format=%cs -- <file>` is the authoritative answer: it is
    verifiable by construction, which is exactly the condition Google states
    for trusting <lastmod>.  When git cannot answer (shallow clone, file not
    yet committed, no git at all) we fall back to the filesystem mtime and
    record it in `self.fallbacks` so the caller can log it loudly.
    """

    def __init__(self, repo_root: pathlib.Path):
        self.repo_root = repo_root
        self.fallbacks: list[str] = []
        self.git_ok = self._probe()

    def _probe(self) -> bool:
        try:
            r = subprocess.run(
                ["git", "-C", str(self.repo_root), "rev-parse", "--git-dir"],
                capture_output=True, text=True, timeout=15,
            )
            return r.returncode == 0
        except (OSError, subprocess.SubprocessError):
            return False

    def _git_date(self, path: pathlib.Path, first: bool = False) -> str | None:
        if not self.git_ok:
            return None
        cmd = ["git", "-C", str(self.repo_root), "log", "--format=%cs"]
        if not first:
            cmd.append("-1")
        cmd += ["--", str(path)]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        except (OSError, subprocess.SubprocessError):
            return None
        if r.returncode != 0:
            return None
        lines = [ln.strip() for ln in r.stdout.splitlines() if ln.strip()]
        if not lines:
            return None
        return lines[-1] if first else lines[0]

    @staticmethod
    def _mtime_date(path: pathlib.Path) -> str:
        ts = path.stat().st_mtime
        return _dt.datetime.fromtimestamp(ts, _dt.timezone.utc).strftime("%Y-%m-%d")

    def last_modified(self, path: pathlib.Path) -> str:
        d = self._git_date(path)
        if d:
            return d
        self.fallbacks.append(str(path))
        return self._mtime_date(path)

    def first_published(self, path: pathlib.Path) -> str:
        d = self._git_date(path, first=True)
        if d:
            return d
        return self.last_modified(path)


def repo_root(start: pathlib.Path | None = None) -> pathlib.Path:
    """Walk up from this file to the repository root (the dir holding landing/)."""
    here = (start or pathlib.Path(__file__)).resolve()
    for p in [here, *here.parents]:
        if (p / LANDING).is_dir() and (p / "scripts").is_dir():
            return p
    return here.parents[2]


def landing_dir(start: pathlib.Path | None = None) -> pathlib.Path:
    return repo_root(start) / LANDING


if __name__ == "__main__":  # pragma: no cover - smoke test
    import doctest

    fails, _ = doctest.testmod()
    root = landing_dir()
    pages = iter_pages(root)
    print(f"landing: {root}")
    print(f"pages:   {len(pages)}")
    for rel in pages[:5]:
        print(f"  {rel:<44} -> {deployed_url(rel)}")
    sys.exit(1 if fails else 0)
